# -*- coding: utf-8 -*-
"""NugasUasML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1djjvYeO2xqW3s0jHq_nKDcJBnv67RrPK
"""

import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt

from google.colab import files
file = files.upload()

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/diabetes.csv')

x_train = df.values
x_train = np.delete(x_train, 8, axis = 1)

y_train = df['Outcome'].values

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/diabetes.csv')

X_test = df.values
X_test = np.delete(X_test, 8, axis = 1)

y_test = df['Outcome'].values

print(x_train)

df.head()

from sklearn.preprocessing import MinMaxScaler

x_train = MinMaxScaler().fit_transform(x_train)
X_test = MinMaxScaler().fit_transform(X_test)

print(x_train)

from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)
clf.fit(x_train, y_train)

y_pred = clf.predict(X_test)

from sklearn.metrics import accuracy_score
round(accuracy_score(y_test, y_pred),3)

df.info()